### ISSUE TITLE
[Mail::Header] modify = 1 and trail whitespaces

### ISSUE THREAD

**Issue by targzeta** [markov2/perl5-MailTools#1]
Hi,
when the modify attribute is on, the final whitespaces are deleted. It is the right thing?
```perl
use Mail::Header;

my $head = Mail::Header->new();
$head->modify(0);
$head->add(Subject => 'Test   ');

$head->modify(1);
$head->add(Subject => 'Test   ');

print $head->as_string();
```

```shell
$> perl test.pl | cat -E
Subject: Test   $
Subject: Test$
```

Thank you in advance,
Emanuele

**Comment by markov2** [comment]
Sorry for not answering earlier...  In think that 'modify' means 'clean-up'.  Trailing white-spaces are usually accidental and unwanted.

Even when a change would be needed here, I would not change it to maintain backward compatibility on this poorly documented feature.
